### ISSUE TITLE
Support for TYPO3 CMS 7.x

### ISSUE THREAD

**Issue by kersten** [jonathanheilmann/ext-jh_opengraphprotocol#12]
Is this plugin already running under typo3 7.x?

**Comment by jonathanheilmann** [comment]
I've tested the current release candidate (https://github.com/jonathanheilmann/ext-jh_opengraphprotocol/releases/tag/v1.1.0-rc3) in a TYPO3 CMS 7.4.0 installation and everything works fine. Actually there are no known bugs.
Earlier versions are not tested yet, but they should work (version 1.0.3 and 1.0.4-rc1)
