### ISSUE TITLE
Compatible with 7.6.0?

### ISSUE THREAD

**Issue by tobias47n9e** [jonathanheilmann/ext-jh_opengraphprotocol#24]
It seems to me that only the backend works with 7.6.0, but none of the information is written into the HTML.

**Comment by jonathanheilmann** [comment]
Did you include the static template as described in documentation? https://docs.typo3.org/typo3cms/extensions/jh_opengraphprotocol/Administrator/Index.html#installation
I'm using this extension in some 7.6 installations and actually there are no known problems.

**Comment by jonathanheilmann** [comment]
Closed due to missing feedback.
