### ISSUE TITLE
Overwrite tags from extbase

### ISSUE THREAD

**Issue by kersten** [jonathanheilmann/ext-jh_opengraphprotocol#25]
Hi,

is it possible to overwrite og: tags from an extbase fe controller?

Greetings

**Comment by jonathanheilmann** [comment]
Hi,

I'm sorry, it is not possible actually.
But it's a great idea to implement a Signal-Slot-Dispatcher to manipulate the generated headers before adding them to $GLOBALS['TSFE'].

Greetings

**Comment by kersten** [comment]
ok, very nice that you agree to that :) I am very new to typo3 and never worked with signal slots. Do you think you have time to implement this in the next days? Otherwise I would give it a try.

**Comment by jonathanheilmann** [comment]
I'll try to do an implementation tomorrow (wednesday) in a dedicated github branch for testing. If it's working I'm going to merge it in master for version 1.2.0

**Comment by kersten** [comment]
Very nice thanks. I know a different issue but, would you mind to add a composer.json that people are able to install it in a composer mode typo3 without using ter composer repository?

**Comment by jonathanheilmann** [comment]
Branch develop_v1.2.0 (https://github.com/jonathanheilmann/ext-jh_opengraphprotocol/tree/develop_v1.2.0) adds SignalSlotDispatcher to the service.

The attached extension writes og data passed via signal to typo3temp/logs/typo3.log (depending on system configuration) and additionally to BE-Users log (see "log" in left menu).
Required files are "ext_localconf.php" and "Classes/Service/SignalService.php"
This extension is only for testing, please uninstall after testing! (It's quick and dirty ;) )


[jh_opengraphprotocol_tests_0.0.1_201604201906.zip](https://github.com/jonathanheilmann/ext-jh_opengraphprotocol/files/228419/jh_opengraphprotocol_tests_0.0.1_201604201906.zip)

**Comment by kersten** [comment]
Many thanks its working. Just added #27 to be able to change the values from the passed array.
