### ISSUE TITLE
Conflicts with news 3.2.4

### ISSUE THREAD

**Issue by gp0** [jonathanheilmann/ext-jh_opengraphprotocol#29]
Basically, duplicate tags get inserted because [news](https://docs.typo3.org/typo3cms/extensions/news/) generates its own opengraph meta tags.

**Comment by gp0** [comment]
Maybe a more general approach would be to check if the meta tags have already been set, but i don't know if this is feasible, looks like the state of the meta tags could be dependent on the loading order of extensions (e.g. jh_opengraphprotocol runs first, but another extension sets meta tags after).

**Comment by jonathanheilmann** [comment]
This typoscript setup solves the problem:
```
[globalVar = GP:tx_news_pi1|news > 0]
temp.tx_jhopengraphprotocol >
page.669 >
[global]
```
What happens here: If tx_news_pi1[news] is a get or post parameter in url, the tags are not generated by jh_opengraphprotocol, but by news.

**Comment by gp0** [comment]
Ah, neat. Thanks. Makes sense after looking at ext-jh_opengraphprotocol/Configuration/TypoScript/setup.txt
