### ISSUE TITLE
Error after including static template “Open Graph protocol”

### ISSUE THREAD

**Issue by frank79a** [jonathanheilmann/ext-jh_opengraphprotocol#39]
I get the following error after including static template “Open Graph protocol” :

Core: Error handler (BE): PHP Warning: vsprintf(): Too few arguments in /var/www/typopro/typo3_src-6.2.25/typo3/sysext/belog/Classes/ViewHelpers/FormatDetailsViewHelper.php line 44

In the frontend, I get a HTTP 500 Internal Server Error.

**Comment by frank79a** [comment]
My Typo3 version is 6.2.25

**Comment by jonathanheilmann** [comment]
I think, this is related to a core bug, i've reported here: https://forge.typo3.org/issues/77444

**Comment by frank79a** [comment]
Thank you!

**Comment by jonathanheilmann** [comment]
Closed, as 6.2 is deprecated.
