### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by pilouf** [jonathanheilmann/ext-jh_opengraphprotocol#48]
TYPO3 7.6.10

I have this error just after installation

```
Argument 1 passed to TYPO3\CMS\Core\Utility\GeneralUtility::removeDotsFromTS() must be of the type array, boolean given, called in typo3conf/ext/jh_opengraphprotocol/ext_tables.php on line 6
```

This code fix the problem : 

```
// Get extension configuration
if (isset($GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf'][$_EXTKEY])){
   $extConf = \TYPO3\CMS\Core\Utility\GeneralUtility::removeDotsFromTS(unserialize($GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf'][$_EXTKEY])); 
}
```

**Comment by maxmishyn** [comment]
I believe that this error will be on all fresh extension installations with PHP7 (undefined $GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf'][$_EXTKEY])

**Comment by olegsv** [comment]
I too have this error.  PHP 5.5.9  , Typo3 6.2.27

**Comment by olegsv** [comment]
I  have this error too.  PHP 5.5.9  , Typo3 6.2.27

**Comment by jonathanheilmann** [comment]
Thanks for reporting and fixing this issue. I've released a new version to TER just now.

**Comment by dermueller** [comment]
This fix did somehow not make it into the repository. ext_tables.php is still uncorrected.
