### ISSUE TITLE
Zip still contains bug #48

### ISSUE THREAD

**Issue by roroettg** [jonathanheilmann/ext-jh_opengraphprotocol#52]
Hello,

while I was downloading and installing the plugin from TER manually, I stumbled over the bug #48. In the zip-file from TER and on the [release-page](https://github.com/jonathanheilmann/ext-jh_opengraphprotocol/releases) in jh_opengraphprotocol_1.2.5.zip the bug still exists.

**Comment by jonathanheilmann** [comment]
That's strange, but I'm going to fix this and release version 1.2.6 this week
