### ISSUE TITLE
Compatibility with TYPO3 8?

### ISSUE THREAD

**Issue by bavarianbytes** [jonathanheilmann/ext-jh_opengraphprotocol#54]
Hi,
is jh_opengraphprotocol compatible with version 8 of TYPO3 or is it planned at least?

**Comment by jonathanheilmann** [comment]
Actually there are no known bugs/issues within TYPO3 8 LTS

**Comment by kersten** [comment]
ok, thats good. but have a look here ;)

https://github.com/jonathanheilmann/ext-jh_opengraphprotocol/blob/v1.2.6/composer.json

**Comment by kersten** [comment]
Thanks :)
