### ISSUE TITLE
Error 500 on update

### ISSUE THREAD

**Issue by erthi16** [jonathanheilmann/ext-jh_opengraphprotocol#58]
Hello!

We've updated from 1.2 to 1.3 and our site crashed with an error 500.  After debugging the file jh_opengraphprotocol/Classes/Service/OgRendererService.php, I've changed several lines to make it work again (all meta tags are correctly inserted now)

My system crached on lines 81, 82 because the class names were not encased in ':
**line 81**: if (class_exists(\Heilmann\JhOpengraphTtnews\Hooks\DisplaySingle::class)) (not working)
**line 81**: if (class_exists('\Heilmann\JhOpengraphTtnews\Hooks\DisplaySingle::class')) (working)
**line 82**: $hookObject = GeneralUtility::makeInstance(\Heilmann\JhOpengraphTtnews\Hooks\DisplaySingle::class); (not working)
**line 82**: $hookObject = GeneralUtility::makeInstance('\Heilmann\JhOpengraphTtnews\Hooks\DisplaySingle::class'); (working)

My system crached also on line 102:
**line 102**: $fileRepository = GeneralUtility::makeInstance(FileRepository::class); (not working)
**line 102 from version 1.2.1**: $fileRepository = GeneralUtility::makeInstance('TYPO3\\CMS\\Core\\Resource\\FileRepository'); (working)

Finaly my system was not able to use the new version of the get url so I changed that section with the one from the 1.2.6 version:
**version 1.3 (not working)**:
        // Get url
        /** @var \TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer $cObj */
        $cObj = $objectManager->get('\TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::class');
        $additionalParams = GeneralUtility::_GET();
        if (GeneralUtility::_GP('L'))
            $additionalParams['L'] = (int)GeneralUtility::_GP('L');
        unset($additionalParams['id']);
        $lConf = [
            'additionalParams' => '&' . GeneralUtility::implodeArrayForUrl('', $additionalParams),
            'parameter' => $GLOBALS['TSFE']->id
        ];
        $og['url'] = htmlentities($cObj->typoLink_URL($lConf));
**version 1.3 (working)**:
        // Get url
	$og['url'] = htmlentities(GeneralUtility::getIndpEnv('TYPO3_REQUEST_URL'));

Our site is using TYPO3 6.2.31 and the PHP version is 5.4.16.

Am I the only one with those problems? Is my setup the cause?

Thank you for your help!

Éric Thibault

**Comment by jonathanheilmann** [comment]
Sorry for my very late reply.
I assume, this is related to the php version you are using. The `::class` constant is available since php 5.5.0
As as least TYPO3 7 LTS requires php 5.5.0, I won't change this.
