### ISSUE TITLE
TYPO3 8 and mergeIfNotBlank Problem

### ISSUE THREAD

**Issue by exinitfrank** [jonathanheilmann/ext-jh_opengraphprotocol#63]
Since TYPO3 8.6 the TCA l10n_mode is removed:
https://docs.typo3.org/typo3cms/extensions/core/Changelog/8.6/Breaking-79243-RemoveL10n_modeMergeIfNotBlank.html

Now, if you look into configuration, all l10n_mode values are removed by TYPO3. The IF in OgRednererService will not work any more:

`if (isset($GLOBALS['TCA']['pages_language_overlay']['columns']['tx_jhopengraphprotocol_ogfalimages']['l10n_mode']) && $GLOBALS['TCA']['pages_language_overlay']['columns']['tx_jhopengraphprotocol_ogfalimages']['l10n_mode'] === 'mergeIfNotBlank')`

You can check the settings of the EXTCONF instead (basic.languageOverlay.tx_jhopengraphprotocol_ogfalimages.mergeIfNotBlank).

**Comment by exinitfrank** [comment]
Yes, this solves the problem.
Thank you.

**Comment by jonathanheilmann** [comment]
I've release version 1.3.2 just now.
