### ISSUE TITLE
Add prefix og: http://ogp.me/ns#

### ISSUE THREAD

**Issue by maechler** [jonathanheilmann/ext-jh_opengraphprotocol#65]
Hi Jonathan

The Open Graph Protocol (http://ogp.me/) requires the prefix for "og" to be set (Although most clients do not care).
It would be great if you could add this to the extension in order to respect the standard and ensure that all clients following the standard do work.

I am not sure however what's the best way to do so. For our site I just added the attribute to `htmlTag_setParams`.

```
config.htmlTag_setParams = prefix="og: http://ogp.me/ns#"
```

But I would not add this to the extensions TypoScript, since it overwrites existing attributes. We could however add this to the documentation.

The second possibility would be to add the prefix to all attributes, that would not require the administrators to add anything to their TypoScript setup.

```
<meta property="http://ogp.me/ns#type" content="website" />
```

What do you think?

**Comment by jonathanheilmann** [comment]
Hi Markus,

actually the extension should add `xmlns:og="http://ogp.me/ns#"` to your html tag, as it applies [this TS line](https://github.com/jonathanheilmann/ext-jh_opengraphprotocol/blob/master/Configuration/TypoScript/setup.txt#L1):
```
config.htmlTag_setParams := appendString( xmlns:og="http://ogp.me/ns#")
```

Doesn't this work in your case? Which TYPO3 version do you use? Is there any other TS overriding the applied setup? (You could check it via TypoScript Object Browser)
![bildschirmfoto 2018-06-20 um 21 59 32](https://user-images.githubusercontent.com/2504896/41681557-4372864e-74d5-11e8-89bb-98057fba86bf.png)

**Comment by jonathanheilmann** [comment]
I’ll add a short note to documentation and update ns declaration to the new recommended approache.

**Comment by jonathanheilmann** [comment]
Actually it's not possible to use the prefix-approach without overriding all other html-tag parameters.
Thus, I've added a how to in documentation with instructions on how to manually use the prefix-approach.

**Comment by maechler** [comment]
Oh, I see..that is a problem indeed. Thank you very much for adding it to the documentation!
