### ISSUE TITLE
og:image:secure_url

### ISSUE THREAD

**Issue by MichiSpandl** [jonathanheilmann/ext-jh_opengraphprotocol#66]
Hi, 
it seems that Facebook has a problem if og:images have a https:// url. In my case the whole page is everytime redirecting to http, so I can't set a http URL. I read about the og:image:secure_url Tag, maybe you could add it? Would be very nice!
Best regards,
Michaela

**Comment by jonathanheilmann** [comment]
Hi,
thanks for your suggestion, I'll add this to version 1.4.0 and would ask you to test branch https://github.com/jonathanheilmann/ext-jh_opengraphprotocol/tree/v1.4.0 (composer) or the attached zip (traditional Extension Manager) [jh_opengraphprotocol_1.4.0-dev_201807020708.zip](https://github.com/jonathanheilmann/ext-jh_opengraphprotocol/files/2153816/jh_opengraphprotocol_1.4.0-dev_201807020708.zip).

**Comment by MichiSpandl** [comment]
Hi,
thanks for setting this up. I have tested it and it works if you choose a pic for a page, but it is not working for the dedault image, because the default image is (in my case) from Typoscript and just a string and no FAL image...

**Comment by jonathanheilmann** [comment]
You are right. I've updated the branch and attached actual version 1.4.0-dev
[jh_opengraphprotocol_1.4.0-dev_201807051959.zip](https://github.com/jonathanheilmann/ext-jh_opengraphprotocol/files/2167690/jh_opengraphprotocol_1.4.0-dev_201807051959.zip)

**Comment by MichiSpandl** [comment]
Looks like it is working now 👍
